---
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare required packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git libcurl4-gnutls-dev libssl-dev libxml2-dev r-base
      - name: Install clir
        run: |
          curl -SO https://raw.githubusercontent.com/dceoy/clir/master/install_clir.sh
          chmod +x install_clir.sh
          ./install_clir.sh
      - name: Set environment variables
        run: |
          echo 'export PATH="${HOME}/.clir/bin:${PATH}"' >> ~/.bash_profile
          echo 'export R_LIBS_USER="${HOME}/.clir/r/library"' >> ~/.bash_profile
      - name: Test configuration
        run: |
          source ~/.bash_profile
          set -x
          clir --version
          clir config
          clir cran --list
          clir cran https://cran.ism.ac.jp/
          clir drat dmlc
          clir config
          clir config --init
          set +x
      - name: Test installation
        run: |
          source ~/.bash_profile
          set -x
          clir update
          clir install foreach doSNOW
          clir validate foreach doSNOW
          clir session foreach doSNOW
          set +x
      - name: Test uninstallation
        run: |
          source ~/.bash_profile
          set -x
          clir uninstall foreach doSNOW
          [[ ! -d "${HOME}/.clir/r/library/foreach" ]]
          [[ ! -d "${HOME}/.clir/r/library/doSNOW" ]]
          set +x
      - name: Test downloading
        run: |
          source ~/.bash_profile
          set -x
          clir download tidyverse gridExtra
          ls -l tidyverse* gridExtra*
          set +x
