---
name: Test
on:
  workflow_call:
  workflow_dispatch:
defaults:
  run:
    shell: bash -euox pipefail {0}
    working-directory: .
jobs:
  test-installation:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v5
      - name: Prepare required packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
            git libcurl4-gnutls-dev libfontconfig1-dev libfreetype6-dev \
            libfribidi-dev libharfbuzz-dev libjpeg-dev libpng-dev libssl-dev \
            libtiff5-dev libxml2-dev r-base
      - name: Set environment variables
        run: |
          echo "${HOME}/.clir/bin" >> "${GITHUB_PATH}"
          echo "R_LIBS_USER=${HOME}/.clir/r/library" >> "${GITHUB_ENV}"
      - name: Install clir
        run: |
          ./install_clir.sh
      - name: Test configuration
        run: |
          clir --version
          clir config
          clir cran --list
          clir cran https://cran.ism.ac.jp/
          clir drat dmlc
          clir config
          clir config --init
      - name: Test installation
        run: |
          clir update
          clir install foreach doParallel tidyverse
          clir install --devt=cran foreach doParallel tidyverse
          clir validate foreach doParallel tidyverse
          clir session foreach doParallel tidyverse
      - name: Test uninstallation
        run: |
          clir uninstall foreach doSNOW
          [[ ! -d "${HOME}/.clir/r/library/foreach" ]]
          [[ ! -d "${HOME}/.clir/r/library/doSNOW" ]]
      - name: Test downloading
        run: |
          clir download tidyverse gridExtra
          ls -l tidyverse* gridExtra*
